version: "3.9"

services:
  caddy:
    image: caddy:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/caddy_data:/data
      - $PWD/caddy_config:/config
#      - $PWD/cert:/cert                    ## Optional if we are using self generated certificate
    networks:
      - caddycode
    depends_on:
      - devops-tools

  devops-tools:
    image: codercom/code-server:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    volumes:
      - $PWD/.config:/home/coder/.config
#      - $PWD/.data:/home/coder/.local      ## Optional, persistent volume used for code-server user settings
#      - $PWD/.ssh:/home/coder/.ssh         ## Optional, persistent volume to save ssh key
      - $PWD/project:/home/coder/project
    networks:
      - caddycode

volumes:
  caddy_data:
  caddy_config:
#  cert:                                    ## Optional if we want to use self generated certificate
  project:

networks:
  caddycode: