version: "3.9"

services:
  caddy:
    image: caddy:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/caddy_data:/data
      - $PWD/caddy_config:/config
      - $PWD/cert:/cert
    networks:
      - caddycode
    depends_on:
      - devops-tools

  devops-tools:
    image: codercom/code-server:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    volumes:
      - $PWD/.config:/home/coder/.config
      - $PWD/project:/home/coder/project
    networks:
      - caddycode

volumes:
  caddy_data:
  caddy_config:
  cert:
  project:

networks:
  caddycode: